const PROJECTS = [
    {
        title: 'Restaurant-Saga',
        description: 'An interactive machine learning web app predicting restaurant success based on coordinates in Dhaka using RandomForestRegressor and heatmaps.',
        tech: ['Python'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/Restaurant-Saga',
        accent: '#2a6693',
    },
    {
        title: 'Way-to-BRAC',
        description: 'A Java-based Pathfinder GUI application using graph-based pathfinding systems to map areas, nodes, and calculate multiple optimal routes.',
        tech: ['Java'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/Way-to-BRAC',
        accent: '#4483b0',
    },
    {
        title: 'Gun-detection-with-yolov10',
        description: 'Advanced computer vision model leveraging YOLOv10 for real-time object detection and safety monitoring.',
        tech: ['Python'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/Gun-detection-with-yolov10',
        accent: '#639cc4',
    },
    {
        title: 'Robo-Pekka',
        description: 'A robotics/algorithmic project developed in C++.',
        tech: ['C++'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/Robo-Pekka',
        accent: '#8cb6d5',
    },
    {
        title: 'mango',
        description: 'A TypeScript-based web project.',
        tech: ['TypeScript'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/mango',
        accent: '#1a8a7a',
    },
    {
        title: 'Graph-DSA',
        description: 'DSA practice and graph algorithms implementations.',
        tech: ['Java'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/Graph-DSA',
        accent: '#2a6693',
    },
    {
        title: 'Parking_System',
        description: 'A parking management system.',
        tech: ['Java'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/Parking_System',
        accent: '#4483b0',
    },
    {
        title: 'lab-Sorting',
        description: 'Sorting algorithms and lab assignments.',
        tech: ['Java'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/lab-Sorting',
        accent: '#639cc4',
    },
    {
        title: 'webpath',
        description: 'A front-end web project.',
        tech: ['HTML/CSS'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/webpath',
        accent: '#8cb6d5',
    },
    {
        title: 'parkway',
        description: 'A web interface for parking solutions.',
        tech: ['HTML/CSS'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/parkway',
        accent: '#1a8a7a',
    },
    {
        title: 'TradePulse',
        description: 'A trading/financial data pulse tracker.',
        tech: ['JavaScript'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/TradePulse',
        accent: '#2a6693',
    },
    {
        title: 'drink',
        description: 'A creative UI layout.',
        tech: ['CSS'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/drink',
        accent: '#4483b0',
    },
    {
        title: 'flappy',
        description: 'A web-based game implementation.',
        tech: ['CSS'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/flappy',
        accent: '#639cc4',
    },
    {
        title: 'homepgJuice',
        description: 'Landing page design for a juice brand.',
        tech: ['CSS'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/homepgJuice',
        accent: '#8cb6d5',
    },
    {
        title: 'juice',
        description: 'E-commerce or product display layout.',
        tech: ['CSS'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/juice',
        accent: '#1a8a7a',
    },
    {
        title: 'juicepr',
        description: 'Product presentation site.',
        tech: ['CSS'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/juicepr',
        accent: '#2a6693',
    },
    {
        title: 'management',
        description: 'A management dashboard layout.',
        tech: ['CSS'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/management',
        accent: '#4483b0',
    },
    {
        title: 'market',
        description: 'A marketplace UI or logic implementation.',
        tech: ['JavaScript'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/market',
        accent: '#639cc4',
    },
    {
        title: 'myscrap',
        description: 'Web scraping or data gathering tool.',
        tech: ['Python'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/myscrap',
        accent: '#8cb6d5',
    },
    {
        title: 'structure',
        description: 'Data structures implementation.',
        tech: ['Java'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/structure',
        accent: '#1a8a7a',
    },
    {
        title: 'tukii',
        description: 'A front-end interface project.',
        tech: ['HTML'],
        link: 'https://github.com/Tasrif-Ahmed-Mohsin/tukii',
        accent: '#2a6693',
    },
];